#https://docs.docker.com/registry/deploying/#deploy-your-registry-using-a-compose-file
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 5043:443
    restart: unless-stopped
    links:
      - registry:registry
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
  registry:
    restart: always
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: Registry Realm
      REGISTRY_AUTH_TOKEN_SERVICE: Token services
      REGISTRY_AUTH_TOKEN_ISSUER: Registry token issuer
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /root/certs/bundle
    volumes:
      - /telescope/data:/var/lib/registry
      - /telescope/certs:/certs
      - /telescope/auth:/auth
