#https://docs.docker.com/registry/deploying/#deploy-your-registry-using-a-compose-file
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./config/etc/nginx/conf.d:/etc/nginx/conf.d
  
  # SSL certificate management for nginx
  certbot:
    image: certbot/certbot
    container_name: 'certbot'
    volumes:
      - ./config/etc/letsencrypt:/etc/letsencrypt
    restart: always
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
 
  registry:
    restart: always
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: Registry Realm
      REGISTRY_AUTH_TOKEN_SERVICE: Token services
      REGISTRY_AUTH_TOKEN_ISSUER: Registry token issuer
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /root/certs/bundle
    volumes:
      - /mnt/docker0storage/registry:/var/lib/registry
      