#https://docs.docker.com/registry/deploying/#deploy-your-registry-using-a-compose-file
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on: 
      - registry
  
  # SSL certificate management for nginx
  certbot:
    image: certbot/certbot
    container_name: 'certbot'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
 
  registry:
    restart: always
    image: registry:2
    volumes:
      - /mnt/docker0storage/registry:/var/lib/registry
      #- ./config/registry-config.yaml:/config/registry-config.yaml  Untested use of the registry-config.yaml file
