#https://docs.docker.com/registry/deploying/#deploy-your-registry-using-a-compose-file
services:
  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - registry
      - docker_auth
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

  # SSL certificate management for nginx
  certbot:
    image: certbot/certbot
    container_name: 'certbot'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  registry:
    restart: always
    image: registry:2
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./config/registry/config.yml:/etc/docker/registry/config.yml
      - ./config/registry/daemon.json:/etc/docker/daemon.json
      - /mnt/docker0storage/registry:/var/lib/registry

  docker_auth:
    image: cesanta/docker_auth
    volumes:
      - ./config/docker_auth:/config:ro
      - /var/log/docker_auth:/logs
      - /etc/letsencrypt:/etc/letsencrypt
    command: /config/auth_config.yml
    restart: always
