# https://docs.docker.com/registry/configuration/

version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /mnt/docker0storage/registry
http:
  addr: 443:5000 # https://docs.docker.com/registry/configuration/#letsencrypt
  host: docker.cdot.systems
  headers:
    X-Content-Type-Options: [nosniff]
